### ISSUE TITLE
Infinit "LOADING..." while checking some profiles

### ISSUE THREAD

**Issue by luiandresgonzalez** [isaac-art/poh_faces_checker#3]
Hi, 
Checking on certain specific profiles the "LOADING..." button stays forever like that, not issuing an error or any warning (can provide the profile via e-mail if needed). Other profiles work fine. 

Thanks for the tool!

**Comment by isaac-art** [comment]
hey, sure if you send an id i can check if it is throwing any errors server side. it was pretty hastily thrown together so my error logging isnt great ha

I was also updating the local database earlier today so it might have been around the same time and that could be the issue
